// src/app/layout.tsx

import type { Metadata } from "next";
import ThemeRegistry from "@/theme/ThemeRegistry";
import { I18nProvider } from "@/shared/i18n/I18nContext";

export const metadata: Metadata = {
  title: "QuickQR Studio",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <meta
          name="emotion-insertion-point"
          content="emotion-insertion-point"
        />
      </head>
      <I18nProvider>
        <ThemeRegistry>
          <body>{children}</body>
        </ThemeRegistry>
      </I18nProvider>
    </html>
  );
}
